import { Couple, DatePlan, Idea, Memory, Profile } from '@/types/bridge';

// Seed data for running Bridge without Supabase. IDs are stable strings
// so navigation and joins behave like real rows.

export const mockProfiles: Profile[] = [
  {
    id: 'user-you',
    display_name: 'You',
    avatar_url: null,
    created_at: '2026-06-01T18:00:00Z',
  },
  {
    id: 'user-sam',
    display_name: 'Sam',
    avatar_url: null,
    created_at: '2026-06-01T18:05:00Z',
  },
];

export const mockCouple: Couple = {
  id: 'couple-1',
  name: 'Us',
  invite_code: 'BRIDGE-7K2M',
  created_at: '2026-06-01T18:10:00Z',
};

export const mockIdeas: Idea[] = [
  {
    id: 'idea-1',
    couple_id: 'couple-1',
    created_by: 'user-sam',
    title: 'Tiny omakase counter in Sawtelle',
    description: '8 seats, the chef talks you through every course.',
    source_type: 'tiktok',
    source_url: 'https://www.tiktok.com/@food/video/123',
    thumbnail_url: null,
    category: 'fancy',
    tags: ['sushi', 'anniversary'],
    location_name: 'Sawtelle',
    latitude: null,
    longitude: null,
    cost_level: '$$$',
    status: 'shortlisted',
    created_at: '2026-08-02T02:14:00Z',
    updated_at: '2026-08-02T02:14:00Z',
  },
  {
    id: 'idea-2',
    couple_id: 'couple-1',
    created_by: 'user-you',
    title: 'Sunset walk at El Matador',
    description: 'Go an hour before golden hour, bring a blanket.',
    source_type: 'instagram',
    source_url: 'https://www.instagram.com/reel/abc',
    thumbnail_url: null,
    category: 'outdoors',
    tags: ['beach', 'golden hour'],
    location_name: 'Malibu',
    latitude: null,
    longitude: null,
    cost_level: 'free',
    status: 'new',
    created_at: '2026-08-05T21:40:00Z',
    updated_at: '2026-08-05T21:40:00Z',
  },
  {
    id: 'idea-3',
    couple_id: 'couple-1',
    created_by: 'user-sam',
    title: 'Natural wine bar with vinyl nights',
    description: null,
    source_type: 'maps',
    source_url: 'https://maps.google.com/?q=wine+bar',
    thumbnail_url: null,
    category: 'drinks',
    tags: ['wine', 'music'],
    location_name: 'Echo Park',
    latitude: null,
    longitude: null,
    cost_level: '$$',
    status: 'new',
    created_at: '2026-08-08T01:12:00Z',
    updated_at: '2026-08-08T01:12:00Z',
  },
  {
    id: 'idea-4',
    couple_id: 'couple-1',
    created_by: 'user-you',
    title: 'Pottery date night class',
    description: 'Saturday evening classes, book 2 weeks ahead.',
    source_type: 'event',
    source_url: 'https://example.com/pottery',
    thumbnail_url: null,
    category: 'activity',
    tags: ['hands-on', 'date class'],
    location_name: 'Culver City',
    latitude: null,
    longitude: null,
    cost_level: '$$',
    status: 'shortlisted',
    created_at: '2026-08-09T17:03:00Z',
    updated_at: '2026-08-09T17:03:00Z',
  },
  {
    id: 'idea-5',
    couple_id: 'couple-1',
    created_by: 'user-sam',
    title: 'Late-night taco truck crawl',
    description: 'Three trucks, one night. Ranked scorecard.',
    source_type: 'manual',
    source_url: null,
    thumbnail_url: null,
    category: 'cheap',
    tags: ['tacos', 'silly'],
    location_name: 'East Hollywood',
    latitude: null,
    longitude: null,
    cost_level: '$',
    status: 'new',
    created_at: '2026-08-10T05:26:00Z',
    updated_at: '2026-08-10T05:26:00Z',
  },
  {
    id: 'idea-6',
    couple_id: 'couple-1',
    created_by: 'user-you',
    title: 'Rooftop cinema — 90s rom-com month',
    description: null,
    source_type: 'event',
    source_url: 'https://example.com/rooftop-cinema',
    thumbnail_url: null,
    category: 'event',
    tags: ['movies', 'rooftop'],
    location_name: 'DTLA',
    latitude: null,
    longitude: null,
    cost_level: '$$',
    status: 'done',
    created_at: '2026-07-11T19:00:00Z',
    updated_at: '2026-07-20T19:00:00Z',
  },
];

export const mockPlans: DatePlan[] = [
  {
    id: 'plan-1',
    couple_id: 'couple-1',
    created_by: 'user-you',
    title: 'Friday: wine, then whatever',
    scheduled_at: '2026-08-21T02:00:00Z',
    location_name: 'Echo Park',
    vibe: 'casual',
    estimated_cost: '$$',
    notes: 'No plans after 10 — leave room for the taco truck.',
    itinerary_json: {
      stops: [
        {
          order: 1,
          title: 'Natural wine bar with vinyl nights',
          idea_id: 'idea-3',
          start_time: '7:00 PM',
          duration_minutes: 90,
          note: 'Grab the corner table by the record player.',
        },
        {
          order: 2,
          title: 'Late-night taco truck crawl',
          idea_id: 'idea-5',
          start_time: '8:45 PM',
          duration_minutes: 75,
          note: 'Start with the al pastor truck.',
        },
      ],
      total_minutes: 165,
      budget_estimate: '$40–70 for two',
      backup: {
        idea_id: 'idea-2',
        title: 'Sunset walk at El Matador',
        reason: 'If the bar line is long, chase the sunset instead.',
      },
      generated_by: 'mock',
    },
    status: 'planned',
    idea_ids: ['idea-3', 'idea-5'],
    created_at: '2026-08-11T04:00:00Z',
    updated_at: '2026-08-11T04:00:00Z',
  },
];

export const mockMemories: Memory[] = [
  {
    id: 'memory-1',
    couple_id: 'couple-1',
    date_plan_id: null,
    created_by: 'user-sam',
    title: 'Rooftop cinema, sweater weather',
    occurred_at: '2026-07-19T03:30:00Z',
    location_name: 'DTLA',
    notes:
      'Got there early enough for the good beanbags. You cried at the ending and blamed the wind.',
    song_title: 'Dreams',
    song_artist: 'The Cranberries',
    aesthetic_theme: 'film',
    food_rating: 3,
    vibe_rating: 5,
    value_rating: 4,
    overall_rating: 5,
    would_do_again: true,
    idea_ids: ['idea-6'],
    photos: [],
    created_at: '2026-07-20T16:00:00Z',
    updated_at: '2026-07-20T16:00:00Z',
  },
  {
    id: 'memory-2',
    couple_id: 'couple-1',
    date_plan_id: null,
    created_by: 'user-you',
    title: 'The dumpling place that almost broke us',
    occurred_at: '2026-06-28T02:00:00Z',
    location_name: 'SGV',
    notes: '90 minute wait. Worth it. Barely.',
    song_title: null,
    song_artist: null,
    aesthetic_theme: 'warm',
    food_rating: 5,
    vibe_rating: 3,
    value_rating: 5,
    overall_rating: 4,
    would_do_again: true,
    idea_ids: [],
    photos: [],
    created_at: '2026-06-29T16:00:00Z',
    updated_at: '2026-06-29T16:00:00Z',
  },
];
